### ISSUE TITLE
Issues on LineageOS 18.1

### ISSUE THREAD

**Issue by JanPokorny** [Caticer/caticer-camera#1]
Hello, I have just installed LineageOS 18.1 (Android 11) on my Xiaomi Mi A2 Lite (https://forum.xda-developers.com/t/rom-unofficial-11-0-lineage-os-18-1-xiaomi-a2-lite.4229439/) and decided to try out your camera port. I really like the idea since the stock camera is pretty good (definitely better than LineageOS's stock). Also I have Camera2 API enabled, but I don't suppose that could cause issues for apps that don't use it?

Anyways, letting you know what works and what does not work for me. Mode by mode:
- **Short video** -- ❌ records just audio, video is black
- **Video** -- ❌ does not even start recording
- **Photo** -- ❓ works, but you have to disable "Enhance lowlight photos automatically" and also the face beautify filters. If you leave them on, the final photo will have the chroma channel somehow stretched and distorted:
![image](https://user-images.githubusercontent.com/4580066/114914753-003d6680-9e23-11eb-9934-3b7c1207195f.png)
![image](https://user-images.githubusercontent.com/4580066/114914806-10554600-9e23-11eb-8721-6fc711ae9239.png)
- **Portrait** -- ✅ no issues
- **Square** -- ✅ no issues
- **Panorama** -- ❌ seems to capture the panorama, but then crashes the whole camera when saving
- **Manual** -- ✅ no issues

**Comment by ket0x4** [comment]
Thanks for information. Unfortunately, I don't have time to fix them right now. I will look at it later. I already know the video problems. I've been working on it for a while. different roms give different errors. so best way to helping issues is giving logs.
I need logcat and dmesg.

To take logcat:
`adb logcat -d > logcat.txt`

To take dmesg:
`adb shell su -c dmesg > dmesg.log`

Then upload to gist or something similar and give link

**Comment by JanPokorny** [comment]
Here are the logs (phone restart, open app, take a picture with enhancement on, and then try to take a panorama and crash):
[logs.zip](https://github.com/Caticer/caticer-camera/files/6326052/logs.zip) (apparently you can just drop files to GitHub issues and they get uploaded)

The video issue seems to be random and not appear immediately after reboot, so I accidentally fixed it by rebooting and now can't give the logs until it happens again 🤷‍♂️

Anyways no rush to fix it, stock LineageOS stock camera + Urnyx's 7.3 v2.5 GCam together cover the same functionality for me, even though rather clumsily. (LineageOS cam is just lacking features like portrait mode, and GCam doesn't work with front camera at all, such is life of early adopters 🙃😄)

**Comment by JanPokorny** [comment]
Update: the distort/glitch can happen even without lowlight enhancements, but I'm not sure what triggers it. It happens consistently with the enhancements on, though.

**Comment by ket0x4** [comment]
@JanPokorny Can you try with HDR Pro enabled

**Comment by JanPokorny** [comment]
@JanPokorny HDR Pro was active for the photos that glitched out, but I was never able to trigger it manually: most of the time, HDR Pro works correctly. Thus, it might or might not be related to the issue -- but given that the two triggers so far are face enhancements and lowlight enhancements, it might point at the issue being somewhere in the effect post-processing pipeline.

**Comment by ket0x4** [comment]
[Test.zip](https://github.com/Caticer/caticer-camera/files/6406581/Test.zip)
Can you try this one

**Comment by JanPokorny** [comment]
@Caticer Sadly I was forced to switch away from LineageOS 18.1 to an Android 10-based ROM, since there were other unrelated bugs and issues preventing me from using it as my daily driver, so I'm unable to test this fix. I plan on returning to Android 11 once it's more stable.

**Comment by ket0x4** [comment]
No problem. Have a good day.
